name: Setup Workflow
description: Setup workflow for GitHub Actions

runs:
    using: composite
    steps:
        - uses: pnpm/action-setup@v2.4.0
          with:
              version: 7

        - name: Setup Node.js environment
          uses: actions/setup-node@v3
          with:
              node-version: 18
              cache: pnpm

        - name: Turbo Cache
          id: turbo-cache
          uses: actions/cache@v3
          with:
              path: .turbo
              key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
              restore-keys: |
                  turbo-${{ github.job }}-${{ github.ref_name }}-

        - name: Install dependencies
          run: pnpm install
          shell: bash
